spring.application.name=scheduler-service

server.servlet.context-path=/scheduler-service

# Server
server.port=8085


# LOGGING CONFIGURATION
logging.config=classpath:log4j2-spring.xml
logging.level.root=INFO
logging.level.com.bank.scheduler=DEBUG
logging.level.org.springframework=WARN


eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


resilience4j.circuitbreaker.instances.customerService.register-health-indicator=true
resilience4j.circuitbreaker.instances.customerService.sliding-window-size=5
resilience4j.circuitbreaker.instances.customerService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.customerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerService.wait-duration-in-open-state=10s





