spring.application.name=scheduler-service

server.servlet.context-path=/scheduler-service

# Server
server.port=8085


# LOGGING CONFIGURATION
# ===============================

# Tell Spring Boot to use log4j2 config file
logging.config=classpath:log4j2-spring.xml

# Default log level
logging.level.root=INFO

# Package-specific logging
logging.level.com.bank.scheduler=DEBUG

# Reduce Spring framework logs
logging.level.org.springframework=WARN